[Integration guide] Add document
HubRise/website pull request #162
Opened 2020-10-13 08:17 UTC by atorin

2020-10-14 10:03 UTC, antmonnier requested changes
Hi Alberto. Don't let the number of suggestions fool you: you did a great job! The amount of feedback just reflects the importance of this page.

Last bits of feedback: this page should be renamed "Integration guide" (title + filename & path). The main /developers page should be updated with the new name, and it should describe this guide as an "Integration checklist and best practices to build your integration" (or sth similar)

2020-10-14 10:03 UTC, antmonnier commented on content/developers/en/integration.md
> +For other tips and suggestions, check our [Integration Sheet](https://docs.google.com/spreadsheets/d/1df-QRlD9h8M58bpFoFaCEzU5pbmYSeHXOLqIVip9-5s/edit?usp=sharing).
Every time we refer to the Integration Sheet, I think we should designated the Tab in which they will find the information.
Some developers may not even realize the sheet contains several tabs.

2020-10-14 13:13 UTC, janainawittner commented
@atorin, @antmonnier, I removed myself as a reviewer. When you guys are ready, if you would like me to go over it, just ping me again :-)

2020-10-15 09:57 UTC, atorin commented on content/developers/en/integration.md
> +This document provides all the information you need to integrate your solution with HubRise.
You're right! :)

2020-10-15 09:58 UTC, atorin commented on content/developers/en/integration.md
> +Some general best practices are applicable to most integrations. But we know that every solution is different, so we will give specific suggestions for different types of case scenarios (online order
I agree that this information is a bit hidden with this format, but I'm not sure about a bullet list with only 2 items. 
How about we rely on a hyperlink to make this info stand out? We can add another for "general best practices", so we get a mini TOC inside the sentence...

2020-10-15 10:01 UTC, antmonnier commented on content/developers/en/integration.md
> +Some general best practices are applicable to most integrations. But we know that every solution is different, so we will give specific suggestions for different types of case scenarios (online order
I'm happy with any solution, as long as it highlights the structure of the document (even for a reader scanning through)

2020-10-15 10:31 UTC, atorin commented on content/developers/en/integration.md
> +You can then provide access to your HubRise account to as many individual users as you want (such as <alice@your-solution.com> or <bob@your-solution.com>).
Yes, my bad! There was a misunderstanding on my part.

2020-10-15 10:33 UTC, atorin commented on content/developers/en/integration.md
> +This is good for your SEO and ours. It also helps maximising transparency by showing exactly what your integration does.
OK! Used a bullet list instead, but I can revert back to a single sentence if that's too much.

2020-10-15 10:33 UTC, atorin commented on content/developers/en/integration.md
> +You should also anonymise customers immediately if they request so, or if they have been inactive for a certain period of time (for example, 3 years). This is a legal requirement in the EU under GDPR
OK, I agree.

2020-10-15 10:33 UTC, atorin commented on content/developers/en/integration.md
> +- Times, encoded in the timezone of the store. Expected delivery times should always be in the future or `null`.
Good idea!

2020-10-15 14:30 UTC, antmonnier commented
In OLO, we should probably separate "Pushing orders" in two sections: "Pushing orders" and "Receiving status updates"

In the new section, please mention that the OLO should monitor order statuses and raise an alert (email to the restaurant managers and/or to the customer) if an order is still in `new` status after a delay of 5 minutes (or so)

2020-10-15 15:07 UTC, merged