[Apps] Filter by name or category (WIP)
HubRise/website pull request #882
Opened 2023-10-13 20:08 UTC by felixlopz

Issue:  https://github.com/HubRise/website/issues/880

2023-10-16 16:46 UTC, antmonnier commented
Sorry @felixlopz for #[46c394c](https://github.com/HubRise/website/pull/882/commits/46c394caf441cc082f0612bd295eab4725ccc166)
Thought I was committing in `master` - I'm feeling stupid :)

2023-10-16 18:32 UTC, antmonnier commented
@felixlopz When you are done with this PR, you can assign it to me for review.

2023-10-16 18:39 UTC, felixlopz commented
> @felixlopz When you are done with this PR, you can assign it to me for review.

Perfect just added you as reviewer, I had sent a few messages through upwork to let you know it was ready

2023-10-16 18:54 UTC, antmonnier requested changes

2023-10-16 18:54 UTC, antmonnier commented on content/developers/en/quick-start.md
> -As an optional step, you can set up a second application that listens to the events generated by the first application via a callback mechanism. To do this, you will first need to create a second OAu
Sorry for this...

2023-10-16 18:54 UTC, antmonnier commented on src/layouts/Apps/Nav/Styles.ts
> +export const CategoryFitler = styled.span`
You can use `mixin.clickable` to avoid this when we click the link and sligthly move the link at the same time:

![image](https://github.com/HubRise/website/assets/5095197/d3e05205-4036-452c-be1d-6de227aa0d48)

2023-10-16 18:54 UTC, antmonnier commented on src/layouts/Apps/Nav/Styles.ts
> +export const SearchWrapper = styled.div`
Add horizontal padding for mobile display:

![image](https://github.com/HubRise/website/assets/5095197/af3b5bb6-7427-4db0-966d-cea6e4b48a82)

2023-10-16 18:54 UTC, antmonnier commented on src/layouts/Apps/Nav/Styles.ts
> +export const SearchWrapper = styled.div`
And in sticky mode, the padding should be green, like this:
![image](https://github.com/HubRise/website/assets/5095197/da463959-07db-4d8a-9b2a-fd93b086abca)

2023-10-16 18:54 UTC, antmonnier commented on src/layouts/Apps/index.tsx
> +  const onSearchInputChange = (value: string) => {
I'm having second thoughts... Considering the small number of apps, I think we should not allow both filters to work simultaneously. Setting one filter should reset the other.

My concern is that users may not find an app by name, and not realise that they selected the wrong category...

2023-10-16 18:54 UTC, antmonnier commented on src/layouts/Apps/index.tsx
> +      if (filteredApps.length < 0) {
Did you mean `<=`?

2023-10-16 18:54 UTC, antmonnier commented on src/layouts/Apps/index.tsx
> +  const isThereAppResults = React.useMemo(() => {
The filtering logic is duplicated from AppGroup. This may result to inconsistencies, for example if we later decide to change the logic here and forget to update it there.

What about making AppGroup return `null` (instead of `<></>`) if there is no match, and show NoResult if all AppGroups evaluate to `null`?

2023-10-16 21:20 UTC, antmonnier commented
I'm just thinking that it could be worth adding one or two cypress tests for filtering. I tend not to write many cypress tests, because they are slow, but a couple of simple tests validating the common use cases is a valuable safety net.

2023-10-18 20:07 UTC, antmonnier approved these changes

2023-10-18 21:30 UTC, merged